requirements: Update 'Flake8'
fyntex/lib-cl-sii-python pull request #273
Opened 2022-02-07 18:12 UTC by ycouce-cdd

Changelog:

- 4.0.1 (2021-10-11):
  https://flake8.pycqa.org/en/latest/release-notes/4.0.1.html
- 4.0.0 (2021-10-10):
  https://flake8.pycqa.org/en/latest/release-notes/4.0.0.html
- 3.9.2 (2021-05-08):
  https://flake8.pycqa.org/en/latest/release-notes/3.9.2.html
- 3.9.1 (2021-04-15):
  https://flake8.pycqa.org/en/latest/release-notes/3.9.1.html
- 3.9.0 (2021-03-14):
  https://flake8.pycqa.org/en/latest/release-notes/3.9.0.html
- 3.8.4 (2020-10-02):
  https://flake8.pycqa.org/en/latest/release-notes/3.8.4.html

Code diff: https://github.com/PyCQA/flake8/compare/3.8.3...4.0.1

2022-02-07 19:56 UTC, fpinto-cdd approved these changes

2022-02-08 03:58 UTC, jtrobles-cdd requested changes
- [ ] Commit message includes changelog for version `3.8.4`, which is the version that is already installed.
- [ ] Code diff in commit message starts at version `3.8.3`, but the current version is `3.8.4`.

2022-02-08 14:16 UTC, ycouce-cdd commented
> * [x]  Commit message includes changelog for version `3.8.4`, which is the version that is already installed.
> * [x]  Code diff in commit message starts at version `3.8.3`, but the current version is `3.8.4`.

Good catch, thanks.

2022-02-08 16:11 UTC, jtrobles-cdd approved these changes

2022-02-08 18:25 UTC, merged