chore: Add support for Python 3.10
fyntex/lib-cl-sii-python pull request #409
Opened 2022-12-28 20:44 UTC by svillegas-cdd

* Add Python 3.10 to Setuptools script.
* Add Tox environment for Python 3.10.
* Add Python 3.10 to CircleCI configuration.
* Add Python 3.10 .black target-version

2022-12-28 21:27 UTC, ycouce-cdd reviewed
Please, add a reference to the new features included in this new version of Python, e.g.

> "More information: https://docs.python.org/3.10/whatsnew/3.10.html"

Both in the commit message and in the description of the PR.

On the other hand, we should also update the version of Python used in the CI jobs, will we do it in this PR @jtrobles-cdd ?

https://github.com/fyntex/lib-cl-sii-python/blob/e07eddc79ea03839421e9d4dcfbaddcc2d372104/.circleci/config.yml#L87

https://github.com/fyntex/lib-cl-sii-python/blob/e07eddc79ea03839421e9d4dcfbaddcc2d372104/.circleci/config.yml#L121

2022-12-28 21:27 UTC, ycouce-cdd commented on .circleci/config.yml
> +                - "3.10.6"
I think we should use the final available version 3.10.9

```suggestion
                - "3.10.9"
```

Ref: https://docs.python.org/3.10/whatsnew/changelog.html#python-3-10-9-final

2022-12-28 21:31 UTC, fpinto-cdd requested changes

2022-12-28 21:31 UTC, fpinto-cdd commented on .circleci/config.yml
> +                - "3.10.6"
Here we should test for version 3.10.9 since it is the latest release

2022-12-29 14:57 UTC, ycouce-cdd approved these changes

2022-12-29 20:42 UTC, fpinto-cdd approved these changes

2022-12-29 21:38 UTC, merged

2023-01-09 16:37 UTC, jtrobles-cdd reviewed
:heavy_check_mark: